development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: postgres
  database: specifications_development
  port: 5432

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: postgres
  database: specifications_test
  port: 5432
